## Лабораторная работа №1 | Вариант 4

Выполнил: Клименко В.М. М8О-303Б-22

### 1. Numpy

In [1]:
import numpy as np
np.set_printoptions(precision=4)

1. Найти индексы не нулевых элементов массива [1,2,0,0,4,0]

In [2]:
arr = [1, 2, 0, 0, 4, 0]
np.nonzero(arr)[0]

array([0, 1, 4])

2. Создайте единичную матрицу размером 3х3

In [3]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

3. Создайте матрицу-шахматную доску 8х8 используя функцию `tile`

In [4]:
np.tile([['□', '■'], ['■', '□']], (4, 4))

array([['□', '■', '□', '■', '□', '■', '□', '■'],
       ['■', '□', '■', '□', '■', '□', '■', '□'],
       ['□', '■', '□', '■', '□', '■', '□', '■'],
       ['■', '□', '■', '□', '■', '□', '■', '□'],
       ['□', '■', '□', '■', '□', '■', '□', '■'],
       ['■', '□', '■', '□', '■', '□', '■', '□'],
       ['□', '■', '□', '■', '□', '■', '□', '■'],
       ['■', '□', '■', '□', '■', '□', '■', '□']], dtype='<U1')

4. Дан 1D массив, удалите все элементы которые входят в диапазон `[3, 8]` inplace

In [5]:
arr = [0, 4, 4, 2, 1, 4, 8, 7, 10, 15]
np.delete(arr, np.s_[3:8]) # np.s_[3:8] = (3, 4, ..., 8) https://numpy.org/doc/stable/reference/generated/numpy.s_.html

array([ 0,  4,  4, 10, 15])

5. Создайте случайный вектор размером 10 элементов и замените максимальный элемент на 0

In [6]:
arr = np.random.random(10)
arr[np.argmax(arr)] = 0
arr

array([0.5895, 0.6077, 0.5841, 0.0184, 0.3078, 0.2074, 0.    , 0.7163,
       0.2924, 0.2344])

6. Как распечатать все значения в массиве?

In [7]:
np.set_printoptions(threshold=np.inf)
np.random.random((15, 25, 2))

array([[[0.6425, 0.5742],
        [0.6355, 0.8991],
        [0.5239, 0.7732],
        [0.046 , 0.1284],
        [0.301 , 0.8091],
        [0.8755, 0.491 ],
        [0.0181, 0.1224],
        [0.2653, 0.8049],
        [0.1125, 0.6693],
        [0.4294, 0.9332],
        [0.6993, 0.3543],
        [0.47  , 0.4037],
        [0.2313, 0.6509],
        [0.0444, 0.1963],
        [0.9218, 0.095 ],
        [0.3924, 0.1138],
        [0.2286, 0.0694],
        [0.3043, 0.3333],
        [0.2048, 0.7734],
        [0.3007, 0.0474],
        [0.5748, 0.5474],
        [0.513 , 0.9813],
        [0.5976, 0.274 ],
        [0.0324, 0.5881],
        [0.9229, 0.5964]],

       [[0.61  , 0.3784],
        [0.1009, 0.3478],
        [0.4906, 0.8137],
        [0.7981, 0.4615],
        [0.1143, 0.4383],
        [0.9539, 0.6284],
        [0.6628, 0.095 ],
        [0.7067, 0.9843],
        [0.5856, 0.6676],
        [0.8512, 0.0819],
        [0.194 , 0.8673],
        [0.5562, 0.7343],
        [0.2332, 0.4288],
        [0

7. Рассмотрим случайный вектор с формой 100х2, представляющей координаты, и найдем расстояния от точки к точке

In [8]:
coords = np.random.random((100, 2))

In [9]:
# |a - b|^2 = |a|^2 + |b|^2 - 2(a, b)
distances_squared = np.sum(coords**2, axis=1).reshape(-1, 1) + np.sum(coords**2, axis=1) - 2 * np.dot(coords, coords.T)
distances_squared[np.less(distances_squared, 0)] = 0
distances = np.sqrt(distances_squared)
distances

array([[0.0000e+00, 9.8313e-01, 6.7495e-01, 1.9618e-01, 7.6273e-01,
        5.2346e-01, 5.2797e-01, 3.0392e-01, 2.9659e-01, 7.2347e-01,
        3.5157e-01, 6.2512e-02, 6.7350e-01, 1.5408e-01, 9.5051e-01,
        2.2028e-01, 8.8678e-01, 2.3109e-01, 4.5523e-01, 3.1421e-01,
        5.8007e-01, 6.7921e-01, 8.3762e-01, 1.8262e-01, 7.5293e-01,
        9.6504e-01, 2.6265e-01, 5.1329e-01, 1.1539e-01, 2.6886e-01,
        3.8119e-01, 6.0963e-01, 7.4890e-01, 1.4510e-01, 1.5816e-01,
        7.4879e-01, 3.0110e-01, 8.4091e-01, 5.3584e-01, 2.0160e-01,
        7.0743e-01, 4.2935e-01, 1.0017e+00, 1.0057e+00, 2.2553e-01,
        9.9225e-01, 6.5583e-01, 5.3115e-01, 8.5234e-02, 8.4620e-01,
        3.2250e-01, 6.6729e-01, 4.2761e-02, 2.9915e-01, 8.7627e-01,
        5.1230e-01, 2.6690e-01, 4.9120e-01, 8.9486e-01, 7.1534e-01,
        6.2619e-01, 2.0211e-01, 4.6945e-01, 2.5161e-01, 5.2929e-01,
        6.3252e-01, 1.0126e+00, 6.6205e-01, 4.2291e-01, 5.0663e-01,
        2.6125e-01, 7.3656e-01, 7.8829e-01, 6.87

8. Как конвертировать массив float(32 bit) к массиву целых чисел (integer 32 bit) in place?

In [10]:
distances.astype(np.int32)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0,

9. Как прочитать заданный файл?
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [11]:
csv_data = np.genfromtxt('9.csv', delimiter=',', dtype=np.int64)
csv_data

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

10. Какой эквивалент enumerate для numpy массивов?

In [12]:
for i, arr in np.ndenumerate(csv_data):
    print(i, arr)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 6
(1, 1) -1
(1, 2) -1
(1, 3) 7
(1, 4) 8
(2, 0) -1
(2, 1) -1
(2, 2) 9
(2, 3) 10
(2, 4) 11


### 2. Pandas

Найдите ответы на вопросы или выполните действия с предложенным датасетом 

Файл: `russian-housing-market.csv`

```
price_doc - Цена продажи
id - Id транзакции
timestamp - Дата транзакции
full_sq - суммарная площадь в квадратных метрах, включая лоджию, валконы и отдельные нежилые помещения
life_sq - жилая площаль в квадратных метрах, исключая лоджии, балконы и прочие нежилые помещения
floor - для апартаментов, этаж помещения
max_floor - количество этажей в здании
material - материал стен
build_year - год постройки
num_room - количество жилых комнат
kitch_sq - площадь кухни
state - состояние апартаментов
product_type - покупка или инвестиция собственника-арендатора
sub_area - название района
```

In [13]:
import pandas as pd

In [14]:
# Load dataset here
df = pd.read_csv('russian-housing-market.csv')
df

id   timestamp  full_sq  life_sq  floor  max_floor  material  \
0          1  2011-08-20       43     27.0    4.0        NaN       NaN   
1          2  2011-08-23       34     19.0    3.0        NaN       NaN   
2          3  2011-08-27       43     29.0    2.0        NaN       NaN   
3          4  2011-09-01       89     50.0    9.0        NaN       NaN   
4          5  2011-09-05       77     77.0    4.0        NaN       NaN   
...      ...         ...      ...      ...    ...        ...       ...   
30466  30469  2015-06-30       44     27.0    7.0        9.0       1.0   
30467  30470  2015-06-30       86     59.0    3.0        9.0       2.0   
30468  30471  2015-06-30       45      NaN   10.0       20.0       1.0   
30469  30472  2015-06-30       64     32.0    5.0       15.0       1.0   
30470  30473  2015-06-30       43     28.0    1.0        9.0       1.0   

       build_year  num_room  kitch_sq  state   product_type  \
0             NaN       NaN       NaN    NaN     Investment   
1             NaN       NaN       NaN    NaN     Investment   
2             NaN       NaN       NaN    NaN     Investment   
3             NaN       NaN       NaN    NaN     Investment   
4             NaN       NaN       NaN    NaN     Investment   
...           ...       ...       ...    ...            ...   
30466      1975.0       2.0       6.0    3.0     Investment   
30467      1935.0       4.0      10.0    3.0     Investment   
30468         NaN       1.0       1.0    1.0  OwnerOccupier   
30469      2003.0       2.0      11.0    2.0     Investment   
30470      1968.0       2.0       6.0    2.0     Investment   

                   sub_area  price_doc  
0                  Bibirevo    5850000  
1         Nagatinskij Zaton    6000000  
2            Tekstil'shhiki    5700000  
3                    Mitino   13100000  
4                 Basmannoe   16331452  
...                     ...        ...  
30466              Otradnoe    7400000  
30467              Tverskoe   25000000  
30468  Poselenie Vnukovskoe    6970959  
30469          Obruchevskoe   13500000  
30470           Novogireevo    5600000  

[30471 rows x 14 columns]

1. Посчитайте количество записей в датасете с отсутствующей информацией о жилой площади жилого помещения

In [15]:
df['life_sq'].isnull().sum()

np.int64(6383)

2. Предложите способ заменить отсутствующие значения из пункта 1 и реализуйте его. Способ нужно аргументировать(сказать почему это достаточно хорошее приближение)

Предлагаю использовать известные знания об отношении общей площади квартиры к жилой площаде и на основе этого выстроить недостающие данные. Я думал отдельно взять случаи, в которых известна площадь кухни, однако я так и не понял это считается жилым помещением или нет, и в датасете, кажется, оно считается жилой зоной.

In [16]:
life_sq_full_sq_coef = (df['life_sq'] / df[df['life_sq'].notnull()]['full_sq']).quantile()

def new_life_sq(row):
    row['life_sq'] = row['full_sq'] * life_sq_full_sq_coef
    return row


df[df['life_sq'].isnull()] = df[df['life_sq'].isnull()].apply(new_life_sq, axis='columns')
df[df['life_sq'].isnull()].count()

id              0
timestamp       0
full_sq         0
life_sq         0
floor           0
max_floor       0
material        0
build_year      0
num_room        0
kitch_sq        0
state           0
product_type    0
sub_area        0
price_doc       0
dtype: int64

3. Какие значения имеет 25, 50 и 75 перцентили полной площади помещения

In [17]:
(df['full_sq'].quantile(0.25), df['full_sq'].quantile(), df['full_sq'].quantile(0.75))

(np.float64(38.0), np.float64(49.0), np.float64(63.0))

4. Посчитайте среднюю стоимость продажи помещений с общей площадью от 50 до 70 квадратных метров

In [18]:
df[(70 >= df['full_sq']) & (df['full_sq'] >= 50)]['price_doc'].mean()

np.float64(7243041.190994609)

5. Какая максимальная этажность здания представлена в датасете

In [19]:
df['max_floor'].max()

np.float64(117.0)

6. Выявите район с самым дорогим жильем

In [20]:
df.iloc[df['price_doc'].idxmax()]['sub_area']

'Teplyj Stan'

7. Посчитайте среднюю стоимость за квадратный метр жилья в Митино(Mitino)

In [21]:
(df[df['sub_area'] == 'Mitino']['price_doc'] / df[df['sub_area'] == 'Mitino']['full_sq']).mean()

np.float64(171841.39999559196)

8. Посчитайте среднюю площадь комнаты в Бибирево

In [22]:
(df[df['sub_area'] == 'Bibirevo']['life_sq'] / df[df['sub_area'] == 'Bibirevo']['num_room']).mean()

np.float64(16.057185628742516)

9. Проанализируйте есть ли разница в цене между квартирами на 1 и 9 этажах

In [23]:
first_floor = df[df['floor'] == 1]
first_floor_description = first_floor.describe().loc[['mean', '25%', '50%', '75%', 'max'], ['full_sq', 'build_year', 'num_room', 'price_doc']]

ninth_floor = df[df['floor'] == 9]
ninth_floor_description = ninth_floor.describe().loc[['mean', '25%', '50%', '75%', 'max'], ['full_sq', 'build_year', 'num_room', 'price_doc']]

print(f'First floor apartments:\n{first_floor_description}\n')
print(f'Ninth floor apartments:\n{ninth_floor_description}')

First floor apartments:
         full_sq   build_year   num_room     price_doc
mean   49.146354  1857.431854   1.832633  5.739380e+06
25%    35.000000  1962.000000   1.000000  4.357166e+06
50%    44.000000  1969.000000   2.000000  5.569575e+06
75%    56.000000  1979.000000   2.000000  6.852768e+06
max   211.000000  2017.000000  10.000000  3.000000e+07

Ninth floor apartments:
         full_sq   build_year  num_room     price_doc
mean   52.610418  1909.316116  1.926141  6.937583e+06
25%    38.000000  1970.000000  1.000000  4.796500e+06
50%    48.000000  1978.000000  2.000000  6.400000e+06
75%    62.000000  2001.000000  3.000000  8.200000e+06
max   388.000000  2017.000000  5.000000  5.650000e+07


По полученным данным можно сделать несколько выводов:
- в среднем квартиры на девятом этаже строились позже, чем на первом *(что, в целом, логично)*
- количество комнат и площадь квартир на девятом этаже больше чем на первом
- квартиры на девятом этаже в среднем дороже, если не смотреть на другие параметры

Однако, мы можем заметить, что стоимость квадратного метра на первом этаже в среднем в полтора раза выше стоимости квадратного метра на девятом!

In [24]:
square_meter_price_first_floor = (df[df['floor'] == 1]['price_doc'] / df[df['floor'] == 1]['full_sq']).mean()
print(f'Mean square meter price one the first floor: {square_meter_price_first_floor}')
square_meter_price_ninth_floor = (df[df['floor'] == 9]['price_doc'] / df[df['floor'] == 9]['full_sq']).mean()
print(f'Mean square meter price one the ninth floor: {square_meter_price_ninth_floor}')

Mean square meter price one the first floor: 194668.88111133175
Mean square meter price one the ninth floor: 134112.89838289807


10. Найдите минимальную стоимость квартиры с жилой площадью не менее 60 квадратных метров, не менее чем 3мя комнатами и не ниже чем на 5 этаже

In [25]:
df[(df['life_sq']  >= 60) & (df['num_room'] >= 3) & (df['floor'] >= 5)]['price_doc'].min()

np.int64(1000000)

### 3. Визуализация

Используя библиотеки matplotlib/sns/plotly/pandas и набор данных представленный ранее визуализируйте

1. Как менялась средняя цена квартиры в Нагатинском Затоне(Nagatinski Zaton) с течением времени

2. Постройте гистограмму распределения цен на квартиры с общей площадью более 50 кв.метров

3. Визуализируйте количество проданных квартир в разных районах

4. Постройте box plot отображающий распределение полных площадей квартир в Басманном районе

5. Визуализируйте зависимость средней стоимости квартир в зависимости от этажа

6. Покажите как меняется средняя площадь квартир в зависимости от района

7. Постройте график изменения медианной цены на квартиру менее 50 кв. метров за период с 2011 до 2014 года*

\* Задание на доп. балл